#!/bin/bash

cd "$(dirname "$0")" || exi
source ../runtest_func.sh

t "7 1 3 6 7
.#..#.." Yes
t "7 1 3 7 6
.#..#.." No
t "15 1 3 15 13
...#.#...#.#..." Yes
t "15 1 3 15 13
...#.#.#.#.#..." No
t "6 1 2 5 6
..##.." No
t "15 3 5 11 13
##.#.#...#.#.##" Yes
