#!/bin/bash

cd "$(dirname "$0")" || exi
source ../runtest_func.sh

t "@codeformula why is this contest so easy" "codeformula"
t "myon @@c @a @aba@a @@bb bbb @@@@@ @a test  @ space  aaa test @a@a  test@takoyaki" "a
aba
bb
c
takoyaki"
t "no atmark"
