#!/bin/bash

cd "$(dirname "$0")" || exi
source ../runtest_func.sh

t "5 3
96 98 95 100 20" "Yes
No"
t "3 2
1001 869120 1001" "No"
t "15 7
3 1 4 1 5 9 2 6 5 3 5 8 9 7 9" "Yes
Yes
No
Yes
Yes
No
Yes
Yes"
